version: '3.8'

volumes:
  config:
  conda:
  n8n_data:
    external: true
  webapp_ws:
    external: true

services:
  webapp:
    image: wn1980/webapp-devcontainer
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapp
    command: /bin/sh -c "while sleep 1000; do :; done"  #keep container from exiting.
    user: "ubuntu"
    volumes:
      - webapp_ws:/workspace:cached
      - n8n_data:/home/ubuntu/.n8n:cached
      - conda:/home/ubuntu/.conda:cached
      - config:/home/ubuntu/.config:rw
    environment:
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=false
      - N8N_TEMPLATES_ENABLED=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_DIAGNOSTICS_CONFIG_FRONTEND=
      - N8N_DIAGNOSTICS_CONFIG_BACKEND=
      - EXTERNAL_FRONTEND_HOOKS_URLS=
    # ports:
    #   - 5001:5001
